# 当有push的时候触发工作流
on: push

jobs:
  job1:
    # 运行在哪个系统上
    runs-on: ubuntu-latest
    # - 为数组写法
    steps:
      - run: pwd
      - run: ls
  job2:
    # 运行在哪个系统上
    runs-on: windows-latest
    steps:
      - run: node --version